/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baitap_LichTap.gui;


import dao.BaitapDao;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import model.Baitap;

/**
 *
 * @author PC
 */
public class baitap extends javax.swing.JFrame {

    /**
     * Creates new form baitap
     */
    public baitap(int baitapID) {
        codegiaodien(baitapID);
    }

    public void codegiaodien(int baitapID){
        setTitle("Home Gym Tracker");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);
        
        Baitap bt = BaitapDao.getBaitapById(baitapID);

        // Sidebar bên trái
        JPanel panel = new JPanel();
        panel.setBackground(new Color(150, 50, 50));
        panel.setBounds(0, 0, 1920, 1080);
        panel.setLayout(null);
        
        // Tiêu đề "Bài tập"
        JLabel titleLabel = new JLabel("Bài tập", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 30));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setBounds(0, 20, 1280, 40);
        panel.add(titleLabel);

        // Nút quay lại
        JButton backButton = new JButton("<");
        backButton.setBounds(20, 20, 50, 40);
        backButton.setFont(new Font("Arial", Font.BOLD, 20));
        panel.add(backButton);
        
        JPanel contentPanel = new JPanel();
        contentPanel.setBackground(new Color(255, 255, 255));
        contentPanel.setBounds(320, 180, 900, 500);
        contentPanel.setLayout(null); // Nền trắng để nổi bật hơn
        panel.add(contentPanel);
        
        JLabel baiTitle = new JLabel("Bài: " + bt.getTenBaitap());
        baiTitle.setFont(new Font("Arial", Font.BOLD, 20));
        baiTitle.setBounds(30, 20, 200, 30);
        contentPanel.add(baiTitle);

        JLabel mucDo = new JLabel("Mức độ: "+ bt.getMucDo());
        mucDo.setFont(new Font("Arial", Font.PLAIN, 18));
        mucDo.setBounds(30, 60, 200, 30);
        contentPanel.add(mucDo);

        JLabel soSet = new JLabel("Số SET: "+ bt.getSoSet());
        soSet.setFont(new Font("Arial", Font.PLAIN, 18));
        soSet.setBounds(30, 90, 200, 30);
        contentPanel.add(soSet);

        JLabel soReps = new JLabel("Số REPS: "+ bt.getSoRep());
        soReps.setFont(new Font("Arial", Font.PLAIN, 18));
        soReps.setBounds(30, 120, 200, 30);
        contentPanel.add(soReps);

        JLabel calo = new JLabel("Calo: "+ bt.getCalo());
        calo.setFont(new Font("Arial", Font.PLAIN, 18));
        calo.setBounds(30, 150, 200, 30);
        contentPanel.add(calo);

        ImageIcon imageIcon = new ImageIcon("C:/duancuoimon/src/logo/hinhanh1.png"); // Đường dẫn hình ảnh
        Image image = imageIcon.getImage().getScaledInstance(550, 450, Image.SCALE_SMOOTH);
        JLabel imageLabel = new JLabel(new ImageIcon(image));
        imageLabel.setBounds(300, 30, 550, 450);
        contentPanel.add(imageLabel);

        // Nút "Bắt đầu"
        JButton startButton = new JButton("Bắt đầu");
        startButton.setBounds(50, 200, 120, 40);
        startButton.setBackground(new Color(200, 50, 50));
        startButton.setForeground(Color.WHITE);
        startButton.setFont(new Font("Arial", Font.BOLD, 16));
        contentPanel.add(startButton);
        
        add(panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baitap(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
